### ISSUE TITLE
对高亮的建议

### ISSUE THREAD

**Issue by haodong** [acgotaku/ShanBayHelper#2]
高亮已经学过的单词神马的完全不能满足需求了有木有
我想要高亮指定词库里的单词可行吗？
比如4级、6级、考研、托福、雅思、GRE等等
额 看了一下扇贝的API，貌似不提供出口
不过我（们）可以帮助提供词库啊 好不好亲~LOL
再狠点的，从指定词库里剔除、或分辨已经学过的单词，这样是不是更叼炸天了！
O(∩_∩)O~~

**Comment by acgotaku** [comment]
@Hasset 如果有需求的话 实现也不是太大的问题 不过确实很久没更新了.... 词库哪里来？

**Comment by Hasset** [comment]
@acgotaku 我会清洗数据，你留个邮箱我发给你一个demo瞧瞧格式行不？~嘿嘿

**Comment by acgotaku** [comment]
@Hasset 邮箱是  acgotaku311  gmail  先发给我词库把 最好是json的 有时间我再把这个项目捡起来 QAQ

**Comment by acgotaku** [comment]
@haldong 那个接口 还是不能用...
